<a href="https://colab.research.google.com/github/Kaniz20/Python_Basics_Libraries_Guide/blob/main/_numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import NumPy Library

In [1]:
import numpy as np

In [2]:
array_name=np.array([1,2,3,4,5]) #parameter--list

In [3]:
type(array_name)

numpy.ndarray

In [4]:
a=np.array([[1,2,3],
            [6,7,8]])

In [5]:
a.shape

(2, 3)

In [6]:
a.ndim

2

In [7]:
array_name.shape,a.shape

((5,), (2, 3))

In [8]:
array_name.dtype,a.dtype

(dtype('int64'), dtype('int64'))

In [9]:
c=np.array([1.0,2,3,4])

#Create an Array

In [10]:
a1=np.array([1,2,3,4,5],dtype="int")
print(a1)

[1 2 3 4 5]


In [11]:
zero=np.zeros((4,4),dtype="int")  #create zero array
print(zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
one=np.ones((4,4),dtype="int") #create one array
print(one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
full_array=np.full((4,4),5) #create full array
print(full_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [14]:
identity=np.identity(4,dtype="int") #create identity matrix
print(identity)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [15]:
eye=np.eye(5,k=2,dtype="int") #create eye matrix
print(eye)

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [16]:
arange=np.arange(1,10,2) #create array with range
print(arange)

[1 3 5 7 9]


In [17]:
linspace=np.linspace(1,5,10,dtype="int")
print(linspace)

[1 1 1 2 2 3 3 4 4 5]


In [20]:
linnspace1=np.linspace(1,5,20,"int")
print(linnspace1)

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


In [29]:
empty=np.empty((1,5))
print(empty)

[[1.80175076e-315 0.00000000e+000 4.94065646e-324             nan
  2.37151510e-322]]


In [31]:
for i in range(5):
  empty[:,i]=i
  empty
  print(empty)

[[0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]]


#Array Indexing and Slicing

In [33]:
r_a=np.random.randint(1,10,size=(5,6))
print(r_a)

[[6 7 3 1 5 2]
 [4 7 3 9 1 3]
 [1 7 7 5 3 2]
 [3 8 7 4 8 3]
 [5 6 2 6 3 7]]


In [35]:
#create 1D array and access one element
a1=np.random.randint(1,7,size=(8))
print(a1)

[3 4 4 3 2 5 6 5]


In [37]:
a1[3]


np.int64(3)

In [38]:
#create 2D array ans access one element
a2=np.random.randint(1,9,size=(7,8))
print(a2)

[[1 3 5 5 3 3 4 8]
 [1 7 5 8 6 1 5 1]
 [1 2 6 8 6 2 1 6]
 [1 5 4 4 3 4 8 5]
 [6 3 2 6 4 7 6 5]
 [8 5 7 5 2 5 7 2]
 [5 8 6 5 5 6 1 2]]


In [39]:
#want to access row2,coloum4 element--8
a2[1,3]  #also write--a2[1][3]

np.int64(8)

In [40]:
#create 3D array
a3=np.random.randint(1,9,size=(2,3,4))
print(a3)

[[[6 6 7 3]
  [6 5 5 3]
  [5 3 8 3]]

 [[2 2 1 7]
  [1 3 5 8]
  [3 2 2 5]]]


In [41]:
a3[0,1,2]

np.int64(5)

In [42]:
print(r_a)

[[6 7 3 1 5 2]
 [4 7 3 9 1 3]
 [1 7 7 5 3 2]
 [3 8 7 4 8 3]
 [5 6 2 6 3 7]]


In [43]:
r_a.size

30

In [44]:
array_name=np.random.randint(1,20,size=(7))
print(array_name)

[14  3  2  3  3 13 17]


In [46]:
array_name[-2]

np.int64(13)

#Slicing

In [47]:
#1D array slicing
x=np.array([1,2,3,4,5,6,7]) #want to slice 1 to 4
print(x[0:4])

[1 2 3 4]


In [48]:
#2D array slicing
#create 2D random array
x1=np.random.randint(1,9,size=(4,5),dtype="int")
print(x1)

[[5 1 1 8 6]
 [5 7 4 5 5]
 [1 3 2 2 3]
 [6 5 4 8 4]]


In [50]:
#1st 2 row slice
x1[0:2]

array([[5, 1, 1, 8, 6],
       [5, 7, 4, 5, 5]])

In [57]:
print(x1[0:2,0:3])


[[5 1 1]
 [5 7 4]]


#Reshape and Resize

In [61]:
r=np.random.randint(1,5,size=(4,6))
print(r)

[[3 3 2 3 4 2]
 [3 2 3 4 4 3]
 [1 2 3 4 3 1]
 [2 1 1 4 3 1]]


In [62]:
reshape=np.reshape(re_shape,(6,4))
print(reshape)


[[2 2 1 3]
 [3 4 2 2]
 [4 2 4 1]
 [3 3 4 1]
 [1 2 1 2]
 [1 4 3 2]]


In [63]:
#resize
re_size=np.resize(r,(6,7))
print(re_size)

[[3 3 2 3 4 2 3]
 [2 3 4 4 3 1 2]
 [3 4 3 1 2 1 1]
 [4 3 1 3 3 2 3]
 [4 2 3 2 3 4 4]
 [3 1 2 3 4 3 1]]


#Ravel and Flatten

**Ravel**

In [66]:
k=np.random.randint(1,10,size=(3,4)) #return a view of the array
print(k)

[[7 6 6 2]
 [5 5 2 6]
 [8 2 4 7]]


In [68]:
ravel=np.ravel(k)  #1D array convert
print(ravel)

[7 6 6 2 5 5 2 6 8 2 4 7]


In [69]:
ravel[0]=1            #1st value 7 exchange with 1
print(ravel)

[1 6 6 2 5 5 2 6 8 2 4 7]


In [70]:
#Now check the main array
print(k) #also change the main array 1st value

[[1 6 6 2]
 [5 5 2 6]
 [8 2 4 7]]


**Flatten**

In [71]:
#create random array
y=np.random.randint(1,10,size=(3,4))
print(y)

[[1 7 2 7]
 [6 9 5 7]
 [4 2 6 1]]


In [73]:
new_y=y.flatten() #return a copy of the array
print(new_y)

[1 7 2 7 6 9 5 7 4 2 6 1]


In [76]:
new_y[0]=10

In [77]:
print(new_y)

[10  7  2  7  6  9  5  7  4  2  6  1]


In [78]:
print(y)

[[1 7 2 7]
 [6 9 5 7]
 [4 2 6 1]]


In [79]:
#new array shape define
arr=np.random.randint(1,10,size=(3,4))
print(arr)

[[7 3 8 3]
 [1 8 9 7]
 [2 3 4 4]]


In [80]:
arr.shape

(3, 4)

In [84]:
arr.shape=(6,2) #array element number same as before
arr


array([[7, 3],
       [8, 3],
       [1, 8],
       [9, 7],
       [2, 3],
       [4, 4]])

#Array Stacking

#Horizontal Stacking

In [85]:
d=np.arange(1,10).reshape(3,3)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
b=3*d
print(b)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [88]:
hori=np.hstack((d,b))
print(hori)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


In [90]:
hori1=np.column_stack((d,b))
print(hori1)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


In [93]:
con=np.concatenate((d,b),axis=1)
print(con)

[[ 1  2  3  3  6  9]
 [ 4  5  6 12 15 18]
 [ 7  8  9 21 24 27]]


#Vertical Stacking


In [91]:
v=np.vstack((d,b))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [92]:
r=np.row_stack((d,b))
print(r)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  6  9]
 [12 15 18]
 [21 24 27]]


/tmp/ipython-input-3207023592.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  r=np.row_stack((d,b))


In [94]:
cc1=np.concatenate((d,b),axis=0)
print(cc1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 3  6  9]
 [12 15 18]
 [21 24 27]]


#Depth Stack

In [95]:
print(b)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [96]:
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
dep=np.dstack((b,d))
print(dep)

[[[ 3  1]
  [ 6  2]
  [ 9  3]]

 [[12  4]
  [15  5]
  [18  6]]

 [[21  7]
  [24  8]
  [27  9]]]
